from pathlib import Path

def once(path, old, new):
    p=Path(path); text=p.read_text(); c=text.count(old)
    if c!=1: raise SystemExit(f'{path}: expected 1, got {c}: {old[:100]!r}')
    p.write_text(text.replace(old,new,1))

once('db/ca-atende.ts', 'function defaultGreeting(context: CaAtendeRuntimeContext) {\n  const link = bookingLink(context.organization.slug);\n  const custom = context.settings.greetingText.trim();\n  if (custom) {\n    const rendered = custom\n      .replaceAll("{barbearia}", context.organization.name)\n      .replaceAll("{link}", link)\n      .trim();\n    const withLink = rendered.includes(link)\n      ? rendered\n      : `${rendered}\\n\\nPara agendar seu horário: ${link}`;\n    return withLink.slice(0,3500);\n  }\n  return `Olá! Seja bem-vindo à ${context.organization.name}. Para agendar seu horário é só acessar: ${link}\\n\\nSe preferir outro assunto, toque em “Ver opções” ou escreva o que precisa.`;\n}', 'function defaultGreeting(context: CaAtendeRuntimeContext) {\n  const link = bookingLink(context.organization.slug);\n  const custom = context.settings.greetingText.trim();\n  if (custom) {\n    return custom\n      .replaceAll("{barbearia}", context.organization.name)\n      .replaceAll("{link}", link)\n      .trim()\n      .slice(0,3500);\n  }\n  return `Olá! Seja bem-vindo à ${context.organization.name}. Como posso te ajudar? Pode escrever do seu jeito ou tocar em “Ver opções”.`;\n}')
once('db/ca-atende.ts', '  // Greeting + link is intentionally local and free. For the rest of natural\n  // conversation, AI is the primary interpreter; rules remain a safe fallback.', '  // Greeting and the guided menu are intentionally local and free. For the rest of natural\n  // conversation, AI is the primary interpreter; rules remain a safe fallback.')
once('db/ca-atende.ts', 'const mainChoices = ["Agendar horário", "Ver horários disponíveis", "Preços e serviços", "Cancelar ou remarcar", "Falar com a barbearia"];\nconst bookingChoices = ["Agendar pelo link", "Quero ajuda por aqui"];', 'const mainChoices = ["Agendar horário", "Ver horários disponíveis", "Preços e serviços", "Cancelar ou remarcar", "Falar com a barbearia"];')
once('db/ca-atende.ts', '  if (normalized === "agendar horario" || normalized === "agendar pelo link") {\n    if (normalized === "agendar pelo link") {\n      return { reply:bookingLink(context.organization.slug), intent:"booking", state:"", memory:{}, source:"rule" };\n    }\n    return { reply:"Como prefere agendar?", intent:"booking", state:"booking_method", memory:{ intent:"booking" }, source:"rule", choices:bookingChoices };\n  }', '  if (normalized === "agendar pelo link") {\n    return { reply:bookingLink(context.organization.slug), intent:"booking", state:"", memory:{}, source:"rule" };\n  }\n  if (normalized === "agendar horario") {\n    return { reply:"Claro. Qual serviço você quer?", intent:"booking", state:"awaiting_service", memory:{ intent:"booking" }, source:"rule", choices:serviceChoices(context) };\n  }')
once('db/ca-atende.ts', '      if (desiredTime) {\n        const exact = slots.filter(slot => slot.time === desiredTime);', '      if (preservedIntent === "booking" && !desiredTime && !afterTime && !beforeTime) {\n        return {\n          reply:"Qual horário você prefere? Pode responder do seu jeito, por exemplo: “15h”, “de manhã” ou “depois das 14h”.",\n          intent:preservedIntent,\n          state:"awaiting_booking_choice",\n          memory:{ ...nextMemory, afterTime:"", beforeTime:"" },\n          source:interpreted.source,\n          dataSource:"agenda",\n        };\n      }\n\n      if (desiredTime) {\n        const exact = slots.filter(slot => slot.time === desiredTime);')
once('tests/ca-atende-conversations.test.mjs', 'test("saudação, opções e link público passam pelo mesmo motor sem IA",async()=>{\n  const [hello,menu,booking,link]=await chat(["oi boa tarde","Ver opções","Agendar horário","Agendar pelo link"]);\n  assert.match(hello.reply,/Barbearia Exemplo/);\n  assert.deepEqual(hello.choices,["Ver opções"]);\n  assert.equal(menu.choices.length,5);\n  assert.deepEqual(booking.choices,["Agendar pelo link","Quero ajuda por aqui"]);\n  assert.equal(link.reply,"https://cortouanotou.com.br/agendar/exemplo");\n  assert.equal(globalThis.__caAiCalls,0);\n});', 'test("saudação conversa primeiro, menu inicia o agendamento e link continua opcional",async()=>{\n  const [hello,menu,booking,link]=await chat(["oi boa tarde","Ver opções","Agendar horário","Agendar pelo link"]);\n  assert.match(hello.reply,/Barbearia Exemplo/);\n  assert.match(hello.reply,/Como posso te ajudar/);\n  assert.doesNotMatch(hello.reply,/https:\\/\\/cortouanotou/);\n  assert.deepEqual(hello.choices,["Ver opções"]);\n  assert.equal(menu.choices.length,5);\n  assert.equal(booking.state,"awaiting_service");\n  assert.match(booking.reply,/Qual serviço/);\n  assert.deepEqual(booking.choices,["Corte","Barba"]);\n  assert.equal(link.reply,"https://cortouanotou.com.br/agendar/exemplo");\n  assert.equal(globalThis.__caAiCalls,0);\n});')
once('tests/ca-atende-conversations.test.mjs', 'test("conversa guiada mantém serviço, data e profissional até confirmação segura",async()=>{\n  const [start,service,barber,day,hour,confirmation]=await chat(["Agendar horário","Quero ajuda por aqui","Corte","Eduardo","amanhã","10"]);\n  assert.equal(service.state,"awaiting_service");\n  assert.equal(barber.state,"awaiting_professional");\n  assert.equal(day.memory.barber,"Eduardo");\n  assert.equal(hour.memory.service,"Corte");\n  assert.equal(confirmation.state,"awaiting_confirmation");\n  assert.equal(confirmation.memory.time,"10:00");\n  assert.deepEqual(confirmation.choices,["Confirmar","Escolher outro horário","Trocar profissional","Cancelar"]);\n  assert.ok(globalThis.__caAiCalls>=1);\n  assert.ok(globalThis.__caSlots.every(slot=>slot.slug==="exemplo" && slot.serviceId===11));\n});', 'test("conversa guiada avança sozinha e pergunta o horário sem despejar a agenda",async()=>{\n  const [start,service,barber,day,confirmation]=await chat(["Agendar horário","Corte","Eduardo","amanhã","10"]);\n  assert.equal(start.state,"awaiting_service");\n  assert.equal(service.state,"awaiting_professional");\n  assert.equal(barber.memory.service,"Corte");\n  assert.equal(day.state,"awaiting_booking_choice");\n  assert.equal(day.memory.barber,"Eduardo");\n  assert.match(day.reply,/Qual horário você prefere/);\n  assert.doesNotMatch(day.reply,/10:00.*11:00.*17:30/);\n  assert.equal(confirmation.state,"awaiting_confirmation");\n  assert.equal(confirmation.memory.time,"10:00");\n  assert.deepEqual(confirmation.choices,["Confirmar","Escolher outro horário","Trocar profissional","Cancelar"]);\n  assert.ok(globalThis.__caAiCalls>=1);\n  assert.ok(globalThis.__caSlots.every(slot=>slot.slug==="exemplo" && slot.serviceId===11));\n});')
