// Keep this inventory tied to real routes, dashboard sections and permissions.
// It explains the product to the interpreter; any numbers must come from tools.
export type ProductKnowledge = {module:string;where:string;who:string;how:string;effects:string;limits:string};
export const productKnowledge:ProductKnowledge[]=[
  {module:"Painel",where:"Painel",who:"dono: equipe inteira; barbeiro: só próprio",how:"Seleciona período, mostra serviços, produtos, mensalidades, custos, comissões e agenda de hoje",effects:"Consultar não altera nada",limits:"Atendimento realizado não é agendamento; resultados dependem do período e registros salvos"},
  {module:"Atendimentos",where:"Registrar",who:"dono e barbeiro no próprio acesso",how:"Avulso ou Mensalista: escolhe cliente, profissional, serviço e pagamento; pode incluir produto",effects:"Gera registro, comissão, taxas e uso do plano quando aplicável",limits:"Barbeiro não edita cortes alheios; serviços inativos não aparecem para novos registros"},
  {module:"Histórico",where:"Histórico",who:"dono: equipe; barbeiro: próprio",how:"Filtra por período e profissional; edita, exclui e exporta Excel",effects:"Alteração ou exclusão atualiza os resultados",limits:"Exclusão pede confirmação; registro agendado não é automaticamente um corte realizado"},
  {module:"Agenda",where:"Agenda",who:"dono: equipe; barbeiro: próprio",how:"Mostra appointments por data e profissional, cria, confirma, remarca ou cancela",effects:"Confirmações/alterações mudam o estado do horário e podem gerar notificação",limits:"Conflitos dependem da duração inteligente; cancelados não contam como horários ocupados"},
  {module:"Agenda inteligente",where:"Configurações > Agenda",who:"dono",how:"Configura expediente por dia e decide se agenda respeita duração dos serviços",effects:"Influencia disponibilidade e sobreposição de novos horários",limits:"Duração do serviço não altera registros avulsos antigos"},
  {module:"Agendamento público",where:"Configurações > Agendamento público",who:"dono configura; qualquer cliente abre link",how:"Ativa link, configura dias, fotos, serviços, profissionais, pagamento e aprovação; o cliente escolhe vaga",effects:"Cria solicitação que pode exigir confirmação",limits:"Sem serviço ativo, horário da equipe, dia aberto ou assinatura válida pode não haver vaga"},
  {module:"Link público",where:"Agendamento público",who:"dono e barbeiro podem copiar/compartilhar",how:"Endereço /agendar/slug da própria barbearia; pode ser aberto ou copiado pelo assistente",effects:"Compartilhar não cria agendamento",limits:"Só o dono configura o link"},
  {module:"Serviços",where:"Configurações > Serviços",who:"dono",how:"Cria serviço com nome, preço, duração e status",effects:"Novo preço/duração vale para novos usos",limits:"Duração entre 5 e 480 minutos; histórico anterior preservado"},
  {module:"Equipe",where:"Equipe > Usuários e convites; Configurações > Equipe",who:"dono",how:"Convida, suspende/reabre acessos e configura comissão e expediente de profissionais",effects:"Permissão restringe dados; mudar horário altera novas vagas",limits:"Suspender não apaga registros nem ganhos"},
  {module:"Comissões",where:"Painel; Configurações > Equipe; Equipe > Vales e pagamentos",who:"dono gerencia; barbeiro consulta próprios valores",how:"Percentual do avulso ou repasse por uso do mensalista; pagamentos são lançados à parte",effects:"Comissão gerada não é pagamento efetuado; gorjeta pertence ao profissional",limits:"Editar comissão atual altera próximos registros e não recalcula pagamentos passados"},
  {module:"Vales e pagamentos",where:"Equipe > Vales e pagamentos; barbeiro: Minha Grana",who:"dono lança; funcionário vê somente o próprio",how:"Registra adiantamentos, pagamentos e fechamentos por profissional",effects:"Ajuda a conciliar saldo gerado e valor recebido",limits:"Não representa transferência bancária automática"},
  {module:"Financeiro",where:"Financeiro",who:"dono",how:"Acompanha receitas, taxas, custos, despesas e metas por período",effects:"Nova despesa altera o resultado financeiro",limits:"Lucro é cálculo sobre dados lançados, não saldo bancário"},
  {module:"Formas de pagamento",where:"Configurações > Pagamentos",who:"dono",how:"Cadastra método e taxa percentual",effects:"Taxa aplicada a registros novos conforme método",limits:"Alterações não reescrevem lançamentos anteriores"},
  {module:"Produtos",where:"Produtos; venda em Registrar",who:"dono e barbeiro segundo acesso",how:"Consulta itens, preço, estoque; venda de produto isolada ou junto de atendimento",effects:"Venda reduz estoque e calcula comissão/custo",limits:"Comissão segue configuração do produto"},
  {module:"Mensalistas",where:"Mensalistas; Configurações > Clientes/Planos",who:"dono administra; barbeiro registra uso permitido",how:"Clientes, pagamentos, saldo de usos, vencimento e plano mensal",effects:"Atendimento mensalista consome uso; pagamento registrado uma vez no faturamento",limits:"Plano arquivado ainda pode constar em históricos; não duplique receita em cada uso"},
  {module:"Notificações",where:"Sino no topo do aplicativo",who:"dono recebe eventos de equipe; barbeiro eventos do próprio horário",how:"Exibe eventos de agendamento e atendimentos conforme assinatura e permissão de push",effects:"Marcar como lida não muda atendimento",limits:"Som/push fora do app dependem de permissão do aparelho e instalação de PWA no iPhone"},
  {module:"Senha e acesso",where:"Entrada > Esqueci minha senha; Configurações > Minha senha",who:"cada usuário",how:"Pede link de redefinição por e-mail ou troca senha autenticado",effects:"Troca de senha encerra sessão",limits:"Assistente nunca pede senha e não vê conteúdo privado de e-mails"},
  {module:"Meu plano",where:"Meu plano",who:"dono",how:"Mostra validade, opções e pagamento da assinatura",effects:"Plano ativo libera área contratada",limits:"Valores são os exibidos no app no momento; assistente não inventa preço"},
  {module:"Afiliados",where:"Plataforma > Afiliados e central própria",who:"administrador da plataforma e afiliados convidados",how:"Convites e links de indicação; acompanha indicação e comissão",effects:"Indicação pode gerar comissão segundo regra atual",limits:"Usuário comum não administra afiliados de outras barbearias"},
  {module:"Barbeiro individual",where:"Cadastro do tipo barbeiro individual; Minha Grana",who:"usuário individual",how:"Mantém seus serviços, agenda, atendimentos e ganhos no próprio espaço",effects:"Registros pertencem à organização individual",limits:"Não vira automaticamente proprietário da barbearia onde trabalha"},
  {module:"Áudio do assistente",where:"Assistente > Microfone",who:"usuário autenticado",how:"Grava áudio real, permite pausar, envia para transcrição e esconde texto até abrir",effects:"A transcrição inicia uma pergunta normal; alterações continuam precisando de confirmação",limits:"Permissão do microfone é controlada por Safari/PWA/Android"},
  {module:"WhatsApp automático",where:"não disponível como automação operacional atual",who:"nenhum",how:"O link público pode ser copiado e enviado manualmente",effects:"Nenhum WhatsApp é enviado pelo assistente",limits:"Nunca afirme que a automação foi ligada ou que mensagem foi enviada"},
];
